---
- name: cr
  block:
    - name: Create the nfs.krestomat.io/v1alpha1.Server
      k8s:
        state: present
        namespace: '{{ namespace }}'
        definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
        wait: yes
        wait_timeout: 300
        wait_condition:
          type: Running
          reason: Successful
          status: "True"
      vars:
        cr_file: 'nfs_v1alpha1_server.yaml'

  always:
    - name: Remove the nfs.krestomat.io/v1alpha1.Server
      when: cr_removal
      k8s:
        state: absent
        namespace: '{{ namespace }}'
        definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
        wait: true
      vars:
        cr_file: 'nfs_v1alpha1_server.yaml'

# - name: Add assertions here
#   assert:
#     that: false
#     fail_msg: FIXME Add real assertions for your operator
