# Install nfs provider operator with rook nfs server permissions
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- server/nfs/crds.yaml
- server/nfs/operator.yaml
# Create Pod Security Policies (Recommended)
# - server/nfs/psp.yaml
# Deploy NFS Admission Webhook (Optional). Requires cert-manager
# - server/nfs/webhook.yaml
# Create Openshift Security Context Constraints (Optional)
# - server/nfs/scc.yaml
patches:
- target:
    kind: CustomResourceDefinition
    name: nfsservers.nfs.rook.io
  patch: |-
    - op: remove
      path: /status
