# permissions for end users to view ganeshas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ganesha-viewer-role
rules:
- apiGroups:
  - nfs.krestomat.io
  resources:
  - ganeshas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nfs.krestomat.io
  resources:
  - ganeshas/status
  verbs:
  - get
