# permissions for end users to edit ganeshas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ganesha-editor-role
rules:
- apiGroups:
  - nfs.krestomat.io
  resources:
  - ganeshas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nfs.krestomat.io
  resources:
  - ganeshas/status
  verbs:
  - get
