---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - pods
      - pods/exec
      - pods/log
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for nfs.krestomat.io/v1alpha1, Kind: Server
  ##
  - apiGroups:
      - nfs.krestomat.io
    resources:
      - servers
      - servers/status
      - servers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for nfs rook
  ##
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nfs.rook.io
    resources:
      - nfsservers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for nfs.krestomat.io/v1alpha1, Kind: Routine
  ##
  - apiGroups:
      - nfs.krestomat.io
    resources:
      - routines
      - routines/status
      - routines/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
