# permissions for end users to edit servers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: server-editor-role
rules:
- apiGroups:
  - nfs.krestomat.io
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nfs.krestomat.io
  resources:
  - servers/status
  verbs:
  - get
