apiVersion: nfs.krestomat.io/v1alpha1
kind: Server
metadata:
  # name should be less than 56 characters
  name: server-sample
spec:
  # Ownership/permissions
  ## Set export folder userid to 48
  server_export_userid: 48
  ## Set export folder groupid to 0
  server_export_groupid: 0
  ## Set export folder permissions to '0775'
  server_export_mode: '0755'

  # Autoexpansion: if storage available is less than 20% or 'server_pvc_autoexpansion_increment_gib', adjust PVC storage size according to 'server_pvc_autoexpansion_increment_gib' and 'server_pvc_autoexpansion_cap_gib':
  # * Kubernetes cluster and (NFS) Server PVC must support expansion of volumes
  # * In older version, (NFS) Server pod may be restart when autoexpanding if Kubernetes feature gate
  #   'ExpandInUsePersistentVolumes' is false. See:
  #   https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
  ## Enable autoexpansion
  server_pvc_autoexpansion: true
  ## Every time autoexpansion is required, increment 5 GiB
  server_pvc_autoexpansion_increment_gib: 5
  ## But no more than 250 GiB
  server_pvc_autoexpansion_cap_gib: 250

  # Other
  ## (NFS) Server PVC initial size in GiB
  server_pvc_init_size_gib: 1

  ## Storage class name to be used by this (NFS) Server
  # server_pvc_data_storage_class_name: standard
