### camelCase
---
apiVersion: nfs.krestomat.io/v1alpha1
kind: Ganesha
metadata:
  # name should be less than 56 characters
  name: ganesha-sample
spec:
  # Ownership/permissions
  ## Set export folder userid to 0
  ganeshaExportUserid: 0
  ## Set export folder groupid to 0
  ganeshaExportGroupid: 0
  ## Set export folder permissions to '0700'
  ganeshaExportMode: '0700'

  # Assign 1Gi for each replica persistent volume
  ganeshaPvcDataSize: 1Gi

  # Enable autoexpansion
  # IMPORTANT:
  # * Kubernetes cluster and pvc MUST support expansion of volumes
  # * In older cluster versions, pods require restart when autoexpanding if Kubernetes feature gate
  #   'ExpandInUsePersistentVolumes' is false. See: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
  # * Rempve ganeshaPvcDataSize
  # Autoexpansion: if storage available is less than 20% or 'ganeshaPvcDataAutoexpansionIncrementGib', adjust PVC storage size according to 'ganeshaPvcDataAutoexpansionIncrementGib' and 'ganeshaPvcDataAutoexpansionCapGib':
  ## Enable autoexpansion
  # ganeshaPvcDataAutoexpansion: true
  ## Every time autoexpansion is required, increment 5 GiB
  # ganeshaPvcDataAutoexpansionIncrementGib: 5
  ## But no more than 25 GiB
  # ganeshaPvcDataAutoexpansionCapGib: 25

  ## Storage class name to be used by this (NFS) Ganesha server
  # ganeshaPvcDataStorageClassName: standard

  ## Generate storage class
  # generate a storage class with this NFS storage as source
  ganeshaGeneratedNfsScNeeded: true

  # Debug
  # ganeshaConfLogLevel: DEBUG
