### camelCase
---
apiVersion: nfs.krestomat.io/v1alpha1
kind: Server
metadata:
  # name should be less than 56 characters
  name: server-sample
spec:
  # Ownership/permissions
  ## Set export folder userid to 0
  serverExportUserid: 0
  ## Set export folder groupid to 0
  serverExportGroupid: 0
  ## Set export folder permissions to '0700'
  serverExportMode: '0700'

  # Autoexpansion: if storage available is less than 20% or 'serverPvcAutoexpansionIncrementGib', adjust PVC storage size according to 'serverPvcAutoexpansionIncrementGib' and 'serverPvcAutoexpansionCapGib':
  # * Kubernetes cluster and (NFS) Server PVC must support expansion of volumes
  # * In older version, (NFS) Server pod may be restart when autoexpanding if Kubernetes feature gate
  #   'ExpandInUsePersistentVolumes' is false. See:
  #   https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
  ## Enable autoexpansion
  serverPvcAutoexpansion: true
  ## Initial pvc size
  serverPvcAutoexpansionInitSizeGib: 1
  ## Every time autoexpansion is required, increment 5 GiB
  serverPvcAutoexpansionIncrementGib: 5
  ## But no more than 250 GiB
  serverPvcAutoexpansionCapGib: 250

  ## Storage class name to be used by this (NFS) Server
  # serverPvcDataStorageClassName: standard

  # Debug
  # serverConfLogLevel: DEBUG
