# Adds namespace to all resources.
namespace: nfs-test

namePrefix: nfs-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

patchesStrategicMerge:
- manager_image.yaml
- debug_logs_patch.yaml
- watch_namespace_patch.yaml
- ../default/manager_auth_proxy_patch.yaml
- ../manager/profile_tasks_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../rbac
- ../manager
images:
- name: testing
  newName: testing-operator
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --zap-devel=true
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --ansible-args='-D'
  target:
    kind: Deployment
