---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.kubernetes

  tasks:
    - import_tasks: kustomize.yml
      vars:
        state: present
