---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.kubernetes

  tasks:
    - import_tasks: kustomize-prepare.yml

    - name: Remove the nfs.krestomat.io/v1alpha1.Server
      when: lookup('k8s', api_version='apiextensions.k8s.io/v1', kind='CustomResourceDefinition', resource_name='servers.nfs.krestomat.io')
      k8s:
        state: absent
        namespace: '{{ namespace }}'
        definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
        wait: true

    - import_tasks: kustomize.yml
      vars:
        state: absent

    - name: Unset pull policy
      command: '{{ kustomize }} edit remove patch --path pull_policy/{{ operator_pull_policy }}.yaml'
      args:
        chdir: '{{ config_dir }}/testing'

    - name: Unset testing image
      command: '{{ kustomize }} edit set image testing=testing-operator'
      args:
        chdir: '{{ config_dir }}/testing'

    - name: Unset testing namespace
      loop:
        - "{{ config_dir }}/testing/nfs/operator"
        - "{{ config_dir }}/testing/nfs/server"
        - "{{ config_dir }}/testing"
      command: '{{ kustomize }} edit set namespace nfs-test'
      args:
        chdir: '{{ item }}'

    - name: Unset testing nameprefix
      command: '{{ kustomize }} edit set nameprefix nfs-'
      args:
        chdir: '{{ config_dir }}/testing'
