apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.1.0/deploy/rbac-csi-nfs.yaml
- https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.1.0/deploy/csi-nfs-driverinfo.yaml
- https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.1.0/deploy/csi-nfs-controller.yaml
- https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.1.0/deploy/csi-nfs-node.yaml
patchesStrategicMerge:
- controller-dnspolicy.yaml
- node-dnspolicy.yaml
