name: Add comment based on labels to PR
on:
  pull_request_target:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'test_group'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add test group comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            /test group
